baseURL = 'https://valueote.pages.dev/'
languageCode = 'zh-cn'
title = 'Valueote'
theme = "PaperMod"

enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = false
ShowToc = true
TocOpen = true

[params.homeInfoParams]
Title = "Hi there ðŸ‘‹, I'm Valueote"
Content = "Welcome to my blog"

[[params.socialIcons]]
name = "github"
url = "https://github.com/valueote"

[menu]

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 40
