baseURL = 'https://valueote.pages.dev/'
languageCode = 'zh-cn'
title = 'Valueote'
theme = "PaperMod"

enableRobotsTXT = true

[params]
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = false

[params.homeInfoParams]
Title = "Hi there ðŸ‘‹"
Content = "I'm Valueote"

[[params.socialIcons]]
name = "github"
url = "https://github.com/valueote"
